import argparse
import base64
import hashlib
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import Literal

import requests
from windows11toast import toast

from PySide6.QtCore import QThread, Signal
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import (
    QApplication,
    QFileDialog,
    QHBoxLayout,
    QHeaderView,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)
from qfluentwidgets import (
    CheckBox,
    FluentIcon,
    FluentTranslator,
    FluentWindow,
    InfoBar,
    LineEdit,
    PrimaryPushButton,
    PushButton,
    StrongBodyLabel,
    SubtitleLabel,
    SwitchButton,
    TableWidget,
    TextEdit,
    Theme,
    setTheme,
)

# 配置信息（也可以通过环境变量传入）
MANIFEST_REPO = "hxabcd/0xabcd-log"
MANIFEST_FILE_PATH = "public/update/EasiAuto.json"
OWNER_REPO = os.getenv("GITHUB_REPOSITORY", "hxabcd/EasiAuto")


def get_sha256(file_path: Path) -> str:
    """计算文件的 SHA256 哈希值"""
    sha256_hash = hashlib.sha256()
    with file_path.open("rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()


def generate_release_body(
    desc: str | None,
    highlights: list[dict[Literal["name", "description"], str]],
    others: list[str],
) -> str:
    """生成美化的 Release Body"""
    body_parts = []

    if desc:
        body_parts.append(f"## 📝 说明\n\n{desc}\n")

    if highlights:
        body_parts.append("## ✨ 亮点功能\n")
        for hl in highlights:
            name = hl.get("name", "").strip()
            description = hl.get("description", "").strip()
            if name:
                body_parts.append(f"- **{name}**: {description}")
        body_parts.append("")

    if others:
        body_parts.append("## 🛠️ 其他更改\n")
        for item in others:
            if item.strip():
                body_parts.append(f"- {item.strip()}")
        body_parts.append("")

    body_parts.append("---")
    body_parts.append("Generated by EasiAuto Release Tool")
    return "\n".join(body_parts)


def create_github_release(version: str, body: str, is_dev: bool, is_draft: bool = False) -> dict:
    """创建 GitHub Release"""
    token = os.getenv("RELEASE_PAT")
    if not token:
        raise ValueError("未找到 TOKEN")

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }

    # 检查 Release 是否已存在
    get_url = f"https://api.github.com/repos/{OWNER_REPO}/releases/tags/v{version}"
    resp = requests.get(get_url, headers=headers)
    if resp.status_code == 200:
        print(f"⚠️ Release v{version} 已存在，将被更新。")
        release_data = resp.json()
        release_id = release_data["id"]
        update_url = f"https://api.github.com/repos/{OWNER_REPO}/releases/{release_id}"

        data = {
            "tag_name": f"v{version}",
            "target_commitish": "main",  # 或者其他分支
            "name": f"EasiAuto v{version}",
            "body": body,
            "draft": is_draft,
            "prerelease": is_dev,
        }
        resp = requests.patch(update_url, headers=headers, json=data)
        resp.raise_for_status()
        return resp.json()

    url = f"https://api.github.com/repos/{OWNER_REPO}/releases"
    data = {
        "tag_name": f"v{version}",
        "target_commitish": "master",
        "name": f"EasiAuto v{version}",
        "body": body,
        "draft": is_draft,
        "prerelease": is_dev,
    }
    resp = requests.post(url, headers=headers, json=data)
    resp.raise_for_status()
    return resp.json()


def upload_asset(upload_url_template: str, file_path: Path):
    """上传 Release 资产"""
    token = os.getenv("RELEASE_PAT")
    filename = file_path.name
    # upload_url 类似于 https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name,label}
    # 需要去掉模板部分
    base_upload_url = upload_url_template.split("{", maxsplit=1)[0]
    upload_url = f"{base_upload_url}?name={filename}"

    headers = {
        "Authorization": f"token {token}",
        "Content-Type": "application/zip",
    }

    print(f"⬆️ 正在上传: {filename} ...")
    with file_path.open("rb") as f:
        resp = requests.post(upload_url, headers=headers, data=f)

    if resp.status_code == 422:
        print(f"⚠️ 资产 {filename} 可能已存在，跳过上传 (或需要手动删除后重试)。")
    else:
        resp.raise_for_status()
    print(f"✅ 上传完成: {filename}")


def update_manifest(
    *,
    dist_dir: Path,
    version: str,
    is_dev: bool,
    confirm_required: bool,
    desc: str | None = None,
    highlights: list[dict[Literal["name", "description"], str]],
    others: list[str],
):
    token = os.getenv("RELEASE_PAT")
    if not token:
        print("错误: 未找到 Token")
        sys.exit(1)

    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"}

    # 1. 获取现有清单内容
    api_url = f"https://api.github.com/repos/{MANIFEST_REPO}/contents/{MANIFEST_FILE_PATH}"
    resp = requests.get(api_url, headers=headers)
    resp.raise_for_status()
    file_data = resp.json()
    manifest = json.loads(base64.b64decode(file_data["content"]).decode("utf-8"))
    sha = file_data["sha"]

    # 2. 准备新版本下载信息
    downloads = []
    # 构建产物命名规则: EasiAuto_{version}(_lite).zip
    for filename in dist_dir.iterdir():
        if filename.suffix == ".zip" and version in filename.name:
            # 简单的 channel 判定逻辑
            channel = "lite" if "lite" in filename.name else "default"

            downloads.append(
                {
                    "channel": channel,
                    "url": f"https://github.com/{OWNER_REPO}/releases/download/v{version}/{filename.name}",
                    "sha256": get_sha256(filename),
                }
            )

    # 3. 构造新版本条目
    new_version_entry = {
        "is_dev": is_dev,
        "confirm_required": confirm_required,
        "description": desc,
        "highlights": highlights,
        "others": others,
        "downloads": downloads,
    }

    # 4. 更新清单
    manifest["versions"][version] = new_version_entry

    # 更新最新版本指针
    if is_dev:
        manifest["latest_dev"] = version
    else:
        manifest["latest"] = version

    # 5. 写回 GitHub
    updated_content = json.dumps(manifest, indent=4, ensure_ascii=False)
    put_data = {
        "message": f"Release {version}",
        "content": base64.b64encode(updated_content.encode("utf-8")).decode("utf-8"),
        "sha": sha,
    }

    put_resp = requests.put(api_url, headers=headers, json=put_data)
    put_resp.raise_for_status()
    print(f"✅ 清单文件已成功更新至版本 {version}")


class BuildThread(QThread):
    log_signal = Signal(str)
    finished_signal = Signal(bool, float)

    def __init__(self, build_types: list[str]):
        super().__init__()
        self.build_types = build_types

    def run(self):
        start_time = time.time()
        for b_type in self.build_types:
            self.log_signal.emit(f"\n🚀 Starting {b_type.upper()} build...\n")
            cmd = ["uv", "run", "python", "tools/build.py", "--type", b_type]

            try:
                # Use subprocess to run the build script
                process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    encoding="utf-8",
                    creationflags=subprocess.CREATE_NO_WINDOW if os.name == "nt" else 0,
                )

                while True:
                    line = process.stdout.readline()
                    if not line and process.poll() is not None:
                        break
                    if line:
                        self.log_signal.emit(line.rstrip())

                if process.returncode != 0:
                    self.log_signal.emit(f"❌ {b_type.upper()} build failed with code {process.returncode}")
                    self.finished_signal.emit(False, 0.0)
                    return

                self.log_signal.emit(f"✅ {b_type.upper()} build completed successfully.")

            except Exception as e:
                self.log_signal.emit(f"❌ Error executing build: {str(e)}")
                self.finished_signal.emit(False, 0.0)
                return

        end_time = time.time()
        self.finished_signal.emit(True, end_time - start_time)


class BuildWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("BuildWidget")
        self.v_layout = QVBoxLayout(self)
        self.v_layout.setContentsMargins(16, 16, 16, 16)
        self.v_layout.setSpacing(12)

        self.title_label = SubtitleLabel("构建", self)
        self.v_layout.addWidget(self.title_label)

        # Build Options
        self.opts_layout = QHBoxLayout()
        self.full_check = CheckBox("Full (Standard)", self)
        self.full_check.setChecked(True)
        self.lite_check = CheckBox("Lite (No CV)", self)
        self.lite_check.setChecked(True)
        self.opts_layout.addWidget(self.full_check)
        self.opts_layout.addWidget(self.lite_check)
        self.opts_layout.addStretch(1)
        self.v_layout.addLayout(self.opts_layout)

        # Build Button
        self.build_btn = PrimaryPushButton("开始构建", self)
        self.build_btn.clicked.connect(self.start_build)
        self.v_layout.addWidget(self.build_btn)

        # Log View
        self.log_view = TextEdit(self)
        self.log_view.setFontFamily("Consolas")
        self.log_view.setReadOnly(True)
        self.log_view.setPlaceholderText("等待构建...")
        self.v_layout.addWidget(self.log_view)

        # Thread reference
        self.build_thread = None
        self.pending_callback = None

    def start_build(self, on_success=None):
        self.pending_callback = on_success
        types = []
        if self.full_check.isChecked():
            types.append("full")
        if self.lite_check.isChecked():
            types.append("lite")

        if not types:
            InfoBar.warning("提示", "请至少选择一种构建类型", parent=self)
            return

        self.build_btn.setEnabled(False)
        self.log_view.clear()

        self.build_thread = BuildThread(types)
        self.build_thread.log_signal.connect(self.append_log)
        self.build_thread.finished_signal.connect(self.on_build_finished)
        self.build_thread.start()

    def append_log(self, text):
        self.log_view.append(text)
        # Scroll to bottom
        sb = self.log_view.verticalScrollBar()
        sb.setValue(sb.maximum())

    def on_build_finished(self, success, duration):
        self.build_btn.setEnabled(True)
        if success:
            time_str = f"{duration:.2f}s"
            if duration > 60:
                m, s = divmod(duration, 60)
                time_str = f"{int(m)}m {s:.2f}s"

            msg = f"构建全部完成，用时: {time_str}"
            InfoBar.success("成功", msg, parent=self)
            toast("EasiAuto Build", msg)
        else:
            InfoBar.error("失败", "构建过程中发生错误", parent=self)
            toast("EasiAuto Build", "❌ 构建失败")
            self.pending_callback = None

        if success and self.pending_callback:
            print("🚀 Executing pending callback (Release)...")
            callback = self.pending_callback
            self.pending_callback = None
            callback()


class ReleaseFormWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("ReleaseFormWidget")

        self.main_layout = QVBoxLayout(self)
        self.main_layout.setContentsMargins(24, 24, 24, 24)
        self.main_layout.setSpacing(12)

        # Title
        self.title_label = SubtitleLabel("发版", self)
        self.main_layout.addWidget(self.title_label)

        # Form Layout

        # Row 1: Version, Is Dev, Confirm
        self.row1_layout = QHBoxLayout()
        self.row1_layout.setSpacing(16)

        self.version_edit = LineEdit(self)
        self.version_edit.setPlaceholderText("版本 (例如 1.1.0)")
        self.version_edit.setFixedWidth(200)
        self.row1_layout.addWidget(self.version_edit)

        self.is_dev_label = StrongBodyLabel("预览版", self)
        self.row1_layout.addWidget(self.is_dev_label)
        self.is_dev_switch = SwitchButton(self)
        self.row1_layout.addWidget(self.is_dev_switch)

        self.confirm_label = StrongBodyLabel("需要确认", self)
        self.row1_layout.addWidget(self.confirm_label)
        self.confirm_switch = SwitchButton(self)
        self.row1_layout.addWidget(self.confirm_switch)

        self.row1_layout.addStretch(1)
        self.main_layout.addLayout(self.row1_layout)

        # Row 2: Token
        self.row2_layout = QHBoxLayout()
        self.token_edit = LineEdit(self)
        self.token_edit.setPlaceholderText("GitHub Token (留空则使用环境变量 RELEASE_PAT)")
        self.token_edit.setEchoMode(LineEdit.EchoMode.Password)
        self.row2_layout.addWidget(StrongBodyLabel("Token:", self))
        self.row2_layout.addWidget(self.token_edit)
        self.main_layout.addLayout(self.row2_layout)

        # Row 3: Dist Dir
        self.row3_layout = QHBoxLayout()
        self.dist_edit = LineEdit(self)
        self.dist_edit.setText("build")
        self.dist_btn = PushButton("选择文件夹", self)
        self.dist_btn.clicked.connect(self.browse_dist)
        self.row3_layout.addWidget(StrongBodyLabel("构建产物目录:", self))
        self.row3_layout.addWidget(self.dist_edit)
        self.row3_layout.addWidget(self.dist_btn)
        self.main_layout.addLayout(self.row3_layout)

        # Description
        self.main_layout.addWidget(StrongBodyLabel("说明:", self))
        self.desc_edit = TextEdit(self)
        self.desc_edit.setFixedHeight(60)
        self.main_layout.addWidget(self.desc_edit)

        # Highlights
        self.main_layout.addWidget(StrongBodyLabel("亮点:", self))
        self.highlights_table = TableWidget(self)
        self.highlights_table.setColumnCount(2)
        self.highlights_table.setHorizontalHeaderLabels(["名称", "描述"])
        self.highlights_table.verticalHeader().hide()
        self.highlights_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.highlights_table.setFixedHeight(140)
        self.main_layout.addWidget(self.highlights_table)

        self.hl_btn_layout = QHBoxLayout()
        self.add_hl_btn = PushButton("添加亮点", self)
        self.add_hl_btn.clicked.connect(self.add_highlight)
        self.remove_hl_btn = PushButton("移除选中", self)
        self.remove_hl_btn.clicked.connect(self.remove_highlight)
        self.hl_btn_layout.addWidget(self.add_hl_btn)
        self.hl_btn_layout.addWidget(self.remove_hl_btn)
        self.hl_btn_layout.addStretch(1)
        self.main_layout.addLayout(self.hl_btn_layout)

        # Others
        self.main_layout.addWidget(StrongBodyLabel("其他更新 (每行一个):", self))
        self.others_edit = TextEdit(self)
        self.others_edit.setFixedHeight(88)
        self.main_layout.addWidget(self.others_edit)

        self.main_layout.addStretch(1)

        self.release_btn = PrimaryPushButton("发版", self)
        self.release_btn.clicked.connect(self.do_release)
        self.release_btn.setFixedHeight(36)

        self.build_release_btn = PrimaryPushButton("构建后发版", self)
        self.build_release_btn.setFixedHeight(36)
        # self.build_release_btn.clicked.connect(...) - connected in ReleaseGUI

        self.btn_layout = QHBoxLayout()
        self.btn_layout.setSpacing(16)
        self.btn_layout.addWidget(self.release_btn)
        self.btn_layout.addWidget(self.build_release_btn)

        self.main_layout.addLayout(self.btn_layout)

    def browse_dist(self):
        path = QFileDialog.getExistingDirectory(self, "选择构建产物目录", self.dist_edit.text())
        if path:
            self.dist_edit.setText(path)

    def add_highlight(self):
        row = self.highlights_table.rowCount()
        self.highlights_table.insertRow(row)
        self.highlights_table.setItem(row, 0, QTableWidgetItem("新功能"))
        self.highlights_table.setItem(row, 1, QTableWidgetItem("描述"))

    def remove_highlight(self):
        row = self.highlights_table.currentRow()
        if row >= 0:
            self.highlights_table.removeRow(row)

    def do_release(self):
        # 1. Validation
        version = self.version_edit.text().strip()
        if not version:
            InfoBar.error("错误", "请输入版本号", parent=self)
            return

        dist_str = self.dist_edit.text().strip()
        dist_dir = Path(dist_str)
        if not dist_dir.exists():
            InfoBar.error("错误", f"构建产物目录未找到: {dist_str}", parent=self)
            return

        token = self.token_edit.text().strip()
        if token:
            os.environ["RELEASE_PAT"] = token

        if not os.getenv("RELEASE_PAT"):
            InfoBar.error("错误", "需要 GitHub Token (请在下方输入或设置 RELEASE_PAT 环境变量)", parent=self)
            return

        # 2. Prepare Data
        desc = self.desc_edit.toPlainText().strip()

        highlights = []
        for row in range(self.highlights_table.rowCount()):
            name_item = self.highlights_table.item(row, 0)
            desc_item = self.highlights_table.item(row, 1)
            if name_item and desc_item:
                highlights.append({"name": name_item.text(), "description": desc_item.text()})

        others_text = self.others_edit.toPlainText().split("\n")
        others = [line.strip() for line in others_text if line.strip()]

        # 3. Call Release
        try:
            self.release_btn.setEnabled(False)
            self.release_btn.setText("发版中...")
            QApplication.processEvents()

            # --- New GitHub Release Logic ---
            body = generate_release_body(desc if desc else None, highlights, others)

            print(f"🚀 创建 GitHub Release v{version} ...")
            release_info = create_github_release(version=version, body=body, is_dev=self.is_dev_switch.isChecked())
            upload_url_template = release_info["upload_url"]

            print("📦 开始上传构建产物...")
            # Upload matching assets
            for filename in dist_dir.iterdir():
                if filename.suffix == ".zip" and version in filename.name:
                    upload_asset(upload_url_template, filename)
            # --------------------------------

            update_manifest(
                dist_dir=dist_dir,
                version=version,
                is_dev=self.is_dev_switch.isChecked(),
                confirm_required=self.confirm_switch.isChecked(),
                desc=desc if desc else None,
                highlights=highlights,
                others=others,
            )

            InfoBar.success("成功", f"版本 {version} 发版成功!", parent=self)

        except Exception as e:
            import traceback

            traceback.print_exc()
            InfoBar.error("发版失败", f"错误: {str(e)}", parent=self, duration=5000)
        finally:
            self.release_btn.setEnabled(True)
            self.release_btn.setText("发版")


class ReleaseGUI(FluentWindow):
    def __init__(self):
        super().__init__()
        setTheme(Theme.AUTO)
        self.setWindowIcon(QIcon("src/EasiAuto/resources/EasiAuto.ico"))
        self.setWindowTitle("EasiAuto 发版工具")
        self.resize(800, 720)

        self.navigationInterface.setExpandWidth(160)
        self.navigationInterface.setCollapsible(False)

        self.build_widget = BuildWidget(self)
        self.release_form_widget = ReleaseFormWidget(self)

        self.addSubInterface(self.build_widget, FluentIcon.DEVELOPER_TOOLS, "构建")
        self.addSubInterface(self.release_form_widget, FluentIcon.UPDATE, "发版")

        # Connect "Build and Release" button
        self.release_form_widget.build_release_btn.clicked.connect(self.handle_build_and_release)

    def handle_build_and_release(self):
        # Switch to build tab to show logs
        self.stackedWidget.setCurrentWidget(self.build_widget)
        # Start build with release callback
        self.build_widget.start_build(on_success=self.release_form_widget.do_release)

        # # Root Layout: Horizontal Split
        # self.root_layout = QHBoxLayout(self)
        # self.root_layout.setContentsMargins(0, 0, 0, 0)
        # self.root_layout.setSpacing(0)

        # # Left: Build Widget
        # self.build_widget = BuildWidget(self)
        # # Right: Release Form Widget
        # self.release_form_widget = ReleaseFormWidget(self)

        # # Add to layout with equal stretch (share space)
        # self.root_layout.addWidget(self.build_widget, 1)
        # self.root_layout.addWidget(self.release_form_widget, 1)


def cmd_update_manifest(args):
    update_manifest(
        dist_dir=Path(args.dist_dir),
        version=args.version,
        is_dev=args.is_dev,
        confirm_required=args.confirm_required,
        desc=args.desc,
        highlights=json.loads(args.highlights),
        others=json.loads(args.others),
    )


def cmd_ui(_):
    app = QApplication(sys.argv)
    translator = FluentTranslator()
    app.installTranslator(translator)
    w = ReleaseGUI()
    w.show()
    sys.exit(app.exec())


def main():
    parser = argparse.ArgumentParser(prog="EasiAuto 发版工具", description="更新远端仓库的 EasiAuto 更新清单文件")
    subparsers = parser.add_subparsers(title="子命令", dest="command")

    # update-manifest 子命令
    update_manifest_parser = subparsers.add_parser("update-manifest", help="更新清单")
    update_manifest_parser.add_argument("--version", required=True, help="版本号, 如 1.1.0")
    update_manifest_parser.add_argument("--is-dev", action="store_true", help="是否为预发布版本")
    update_manifest_parser.add_argument("--confirm-required", action="store_true", help="是否需要确认")
    update_manifest_parser.add_argument("--desc", default="", help="版本描述内容")
    update_manifest_parser.add_argument("--highlights", default="[]", help="JSON 格式的亮点列表")
    update_manifest_parser.add_argument("--others", default="[]", help="JSON 格式的其他更新列表")
    update_manifest_parser.add_argument("--dist-dir", default="build", help="构建产物所在目录")
    update_manifest_parser.set_defaults(func=cmd_update_manifest)

    # ui 子命令
    ui_parser = subparsers.add_parser("ui", help="打开图形界面")
    ui_parser.set_defaults(func=cmd_ui)

    args = parser.parse_args()
    if hasattr(args, "func"):
        args.func(args)
    else:
        cmd_ui(args)


if __name__ == "__main__":
    main()
